language: python
sudo: false
env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py34-flake8
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py27-dj110
  - TOX_ENV=py27-dj111
  - TOX_ENV=py34-dj17
  - TOX_ENV=py34-dj18
  - TOX_ENV=py34-dj19
  - TOX_ENV=py34-dj110
  - TOX_ENV=py34-dj111
install:
 - pip install -r requirements-test.txt
script:
  - tox -e $TOX_ENV
